name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: nervus
          POSTGRES_USER: nervus_user
          POSTGRES_PASSWORD: secure_password
        options: >-
          --health-cmd="pg_isready -U nervus_user -d nervus" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -f authentication/pom.xml

      - name: Run Tests
        run: mvn test -f authentication/pom.xml

      - name: Build Docker Image
        run: |
          cd authentication
          docker build -t nervus-authentication:latest .

      - name: Test Docker Container
        run: |
          cd authentication
          docker run -d --name test-container -p 8080:8080 nervus-authentication:latest
          sleep 10
          docker exec test-container curl http://localhost:8080/api/users || exit 1
          docker stop test-container
          docker rm test-container

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Local Docker
        run: |
          cd authentication
          docker stop nervus-authentication || true
          docker rm nervus-authentication || true
          docker run -d -p 8080:8080 --name nervus-authentication nervus-authentication:latest