version: '3.8'
services:
  authentication:
    image: ghcr.io/nervus-tech/nervus-authentication:v1.1.0
    ports:
      - "8099:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nervus
      - SPRING_DATASOURCE_USERNAME=nervus_user
      - SPRING_DATASOURCE_PASSWORD=secure_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - HIBERNATE_DEFAULT_SCHEMA=local_auth
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=nervus
      - POSTGRES_USER=nervus_user
      - POSTGRES_PASSWORD=secure_password
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: 